[package]
name = "linguistic"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
embed-resource = "1.7.3"

[dependencies]
native-windows-gui = "1.0.13"
native-windows-derive = "1.0.5"